package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseActivityitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activityitem extends BaseActivityitem<Activityitem> {
	public static final Activityitem dao = new Activityitem();
}
