package com.ymhw.website.model;

import java.util.List;

import com.ymhw.website.model.base.BaseActivitybill;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activitybill extends BaseActivitybill<Activitybill> {
	public static final Activitybill dao = new Activitybill();
	
	/**
	 * 查询订单状态 ：（0:待支付,1:支付中,2:支付成功,3:支付失败，4：已关闭） -1 - 继续查询状态（待支付,支付中,订单未入库） 0-支付成功  1-支付失败 （支付失败,已关闭）
	 * @param orderNo
	 * @return
	 */
	public int queryPayStatus(String orderNo) {
		List<Activitybill> list = dao.find("select * from activitybill where billNo = ?", orderNo);
		if (list == null || list.size() == 0)
		{
			return -1;
		}
		Activitybill bill = dao.findFirst("select * from activitybill where billNo = ?", orderNo);
		if (bill.getStatus() == 2) {
			return 0;
		} else if (bill.getStatus() == 3 || bill.getStatus() == 4) {
			return 1;
		} else {
			return -1;
		}
	}
	
	public Activitybill getBillByBillNo(String billNo) {
		return dao.findFirst("select * from activitybill where billNo = ?", billNo);
	}
}
