package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseActivityproperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activityproperty extends BaseActivityproperty<Activityproperty> {
	public static final Activityproperty dao = new Activityproperty();
}
