package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseActivityorderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activityorderdetail extends BaseActivityorderdetail<Activityorderdetail> {
	public static final Activityorderdetail dao = new Activityorderdetail();
}
