package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseActivitytype;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activitytype extends BaseActivitytype<Activitytype> {
	public static final Activitytype dao = new Activitytype();
}
