package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseAdvice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advice extends BaseAdvice<Advice> {
	public static final Advice dao = new Advice();
}
