package com.ymhw.website.model;

import java.util.List;

import com.ymhw.website.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article();
	
	public List<Article> getList(int num)
	{
		if (num <= 0)
		{
			return dao.find("select a.*,u.account from article a,user u where a.isValid = 1 and u.isValid = 1 and a.author = u.id order by a.publishTime desc");
		}
		return dao.find("select a.*,u.account from article a,user u where a.isValid = 1 and u.isValid = 1 and a.author = u.id order by a.publishTime desc limit ?", num);
	}
	
	public List<Article> getListByType(int typeId,int displayNum)
	{
		if (displayNum == 0)
		{
			return dao.find("SELECT a.*,u.account,u.headshot FROM article a,user u WHERE a.isValid =1 and u.isValid = 1 and a.author = u.id  and FIND_IN_SET(?,a.types) > 0 order by a.publishTime desc ", typeId);
		}
		else
		{
			return dao.find("SELECT a.*,u.account,u.headshot FROM article a,user u WHERE a.isValid =1 and u.isValid = 1 and a.author = u.id  and FIND_IN_SET(?,a.types) > 0 order by a.publishTime desc limit ?", typeId,displayNum);
		}
	}
	
	public Article queryOneValid(int id)
	{
		return dao.findFirst("SELECT a.*,u.account,u.headshot,u.motto FROM article a,user u WHERE a.isValid =1 and u.isValid = 1 and a.id = ? and a.author = u.id   order by a.publishTime desc ",id);
	}
}
