package com.ymhw.website.model;

import java.util.List;
import java.util.Map;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.ymhw.website.model.base.BaseCarfactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carfactory extends BaseCarfactory<Carfactory> {
	public static final Carfactory dao = new Carfactory();
	
	/**
	 * 获取所有已通过审核的取车门店
	 * @return
	 */
	public List<Carfactory> getAllFactories() {
		return dao.find("select * from carFactory where checkStatus = 3 and isValid = 1 order by createTime desc");
	}

	public Page<Carfactory> paginateByCondition(int pageNumber, int pageSize, Map<String, Object> param) {
		String keyword = (String) param.get("keyword");
		String sql = "";
		if (StrKit.isBlank(keyword)) {
			sql = "select c.*,u.account from carfactory c, `user` u where c.isValid = 1 and c.userId = u.id order by c.createTime desc";
			return dao.paginate(pageNumber, pageSize, sql);
		} else {
			sql = "select c.*,u.account from carfactory c, `user` u where c.isValid = 1 and c.userId = u.id "
					+ "and (c.name like ? or c.provice like ? or c.city like ? or c.region like ? or c.streetAddress like ?) order by c.createTime desc";
			return dao.paginate(pageNumber, pageSize, sql, "%"+keyword+"%", "%"+keyword+"%", "%"+keyword+"%", "%"+keyword+"%", "%"+keyword+"%");
		}
	}
	
}
