package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseCarorderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Carorderdetail extends BaseCarorderdetail<Carorderdetail> {
	public static final Carorderdetail dao = new Carorderdetail();
	
	public Carorderdetail getOrderDetailByOderNo(String orderNo) {
		return dao.findFirst("select * from carorderdetail where isValid = 1 and orderNo = ?", orderNo);
	}
}
