package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contact extends BaseContact<Contact> {
	public static final Contact dao = new Contact();
}
