package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseEquiporderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equiporderdetail extends BaseEquiporderdetail<Equiporderdetail> {
	public static final Equiporderdetail dao = new Equiporderdetail();
}
