package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback();
}
