package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseFoodorderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Foodorderdetail extends BaseFoodorderdetail<Foodorderdetail> {
	public static final Foodorderdetail dao = new Foodorderdetail();
}
