package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseInfoModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InfoModule extends BaseInfoModule<InfoModule> {
	public static final InfoModule dao = new InfoModule();
}
