package com.ymhw.website.model;

import java.util.List;

import com.ymhw.website.model.base.BaseInfoTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InfoTag extends BaseInfoTag<InfoTag> {
	public static final InfoTag dao = new InfoTag();
	
	/**
	 * 获得对应标签的所有资讯
	 * @param tagId
	 * @return
	 */
	public List<Info> getInfos(Integer tagId) {
		if (tagId == null)
		{
			tagId = this.getTagId();
		}
		return Info.dao.find("select inf.* from info inf, info_has_tag iht where iht.tag_id = ? and inf.info_id = iht.info_id", tagId);
	}
}
