package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseInfoHasTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InfoHasTag extends BaseInfoHasTag<InfoHasTag> {
	public static final InfoHasTag dao = new InfoHasTag();
}
