package com.ymhw.website.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.jfinal.kit.StrKit;
import com.ymhw.website.model.base.BaseOrder;
import com.ymhw.website.utils.DateUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public static final Order dao = new Order();
	
	/**
	 * 查询订单状态 ：（0:待支付,1:支付中,2:支付成功,3:支付失败，4：已关闭） -1 - 继续查询状态（待支付,支付中,订单未入库） 0-支付成功  1-支付失败 （支付失败,已关闭）
	 * @param orderNo
	 * @return
	 */
	public int queryPayStatus(String orderNo) {
		Order bill = dao.findFirst("select * from `order` where orderNo = ?", orderNo);
		if (bill == null)
		{
			return -1;
		}
		
		if (bill.getStatus() == 2) {
			return 0;
		} else if (bill.getStatus() == 3 || bill.getStatus() == 4) {
			return 1;
		} else {
			return -1;
		}
	}
	
	public Order getBillByOrderNo(String orderNo) {
		return dao.findFirst("select * from `order` where orderNo = ?", orderNo);
	}
	
	/**
	 * 根据订单号来查询订单中商品的信息（订单号最后两位是商品类型） type 1-活动订单 2-装备订单 3-车辆订单 4-农家乐中产品订单
	 * @param orderNo
	 * @return
	 */
	public Map<String, String> getProductInfo(String orderNo) {
		String type = orderNo.substring(orderNo.length()-2);
		Map<String, String> map = new HashMap<String, String>();
		String proName = "";
		String proDesc = "";
		if ("01".equals(type)) {
			 
		} else if ("02".equals(type)) {
			
		} else if ("03".equals(type)) {
			List<Carorderdetail> details = Carorderdetail.dao.find("select * from carorderdetail where orderNo = ?", orderNo);
			if (details != null) {
				if (details.size() == 1) {
					Carorderdetail detail = details.get(0);
					Car car = Car.dao.getCarById(detail.getCarId());
					proName = car.getName();
					proDesc = car.getName() + " " + detail.getNum() + "辆   租用时间:"+ 
								DateUtil.date2String(detail.getRentStartTime(), DateUtil.FORMAT0) + "到" +
								DateUtil.date2String(detail.getRentEndTime(), DateUtil.FORMAT0);
				} else {
					//暂时没有做购物车 不存在一个订单中有多种商品的情况
				}
			}
		} else if ("04".equals(type)) {
			List<Productorderdetail> details = Productorderdetail.dao.find("select * from productorderdetail where orderNo = ?", orderNo);
			if (details != null) {
				if (details.size() == 1) {
					Productorderdetail detail = details.get(0);
					Product product = Product.dao.getOneById(detail.getProId());
					proName = product.getTitle();
					String tmp = "";
					if (!StrKit.isBlank(product.getSubhead())) {
						tmp = "(" + product.getSubhead() + ")";
					}
					proDesc = product.getTitle() + tmp + "|数量" + detail.getNum();
				} else {
					//暂时没有做购物车 不存在一个订单中有多种商品的情况
				}
			}
		}
		map.put("proName", proName);
		map.put("proDesc", proDesc);
		return map;
	}
}
