package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseProductorderdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Productorderdetail extends BaseProductorderdetail<Productorderdetail> {
	public static final Productorderdetail dao = new Productorderdetail();
	
	public Productorderdetail getFirst(String orderNo) {
		return dao.findFirst("select * from productorderdetail where isValid = 1 and orderNo = ?", orderNo);
	}
}
