package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	public static final RolePermission dao = new RolePermission();
}
