package com.ymhw.website.model;

import com.ymhw.website.model.base.BaseSignup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Signup extends BaseSignup<Signup> {
	public static final Signup dao = new Signup();
}
