package com.ymhw.website.model;

import java.util.List;
import java.util.Map;

import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.ymhw.website.model.base.BaseStrategy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Strategy extends BaseStrategy<Strategy> {
	public static final Strategy dao = new Strategy();
	
	public List<Strategy> getStrategys(int type, int num) {
		if (num == 0)
		{
			return dao.find("select id,title from strategy where type = ? order by time desc", type);
		}
		else
		{
			return dao.find("select id,title from strategy where type = ?  order by time desc limit ?", type, num);
		}
	}
	
	public List<Strategy> getStrategys(int num) {
		if (num == 0)
		{
			return dao.find("select id,title,type,time from strategy order by time desc");
		}
		else
		{
			return dao.find("select id,title,type,time from strategy  order by time desc limit ?", num);
		}
	}
	
	public Strategy getStrategyById(int id) {
		return dao.findFirst("select * from strategy where isValid = 1 and id = ?", id);
	}
	
	/**
	 * 根据关键字搜索周边目的地
	 * @param keyword
	 * @return
	 */
	public int searchByKeyword(String keyword) {
		Strategy strategy = dao.findFirst("select * from strategy where title like ?", '%' + keyword + '%');
		if (strategy != null) {
			return strategy.getId();
		}
		return 0;
	}
	
	public Page<Strategy> paginateByCondition(int pageNumber, int pageSize, Map<String, Object> param) {
		int type = (int) param.get("type");
		String keyword = (String) param.get("keyword");
		String sql = "";
		if (StrKit.isBlank(keyword) && type == -1) {
			sql = "select s.*,u.account from strategy s, `user` u where s.isValid = 1 and s.userId = u.id order by s.time desc";
			return dao.paginate(pageNumber, pageSize, sql);
		} else if (StrKit.isBlank(keyword) && type != -1) {
			sql = "select s.*,u.account from strategy s, `user` u where s.isValid = 1 and s.type = ? and s.userId = u.id order by s.time desc";
			return dao.paginate(pageNumber, pageSize, sql, type);
		} else if (!StrKit.isBlank(keyword) && type == -1) {
			sql = "select s.*,u.account from strategy s, `user` u where s.isValid = 1 and s.title like ? and s.userId = u.id order by s.time desc";
			return dao.paginate(pageNumber, pageSize, sql, "%"+keyword+"%");
		} else {
			sql = "select s.*,u.account from strategy s, `user` u where s.isValid = 1 and s.type = ? and s.title like ? and s.userId = u.id order by s.time desc";
			return dao.paginate(pageNumber, pageSize, sql, type, "%"+keyword+"%");
		}
	}
}
