package com.ymhw.website.model;

import java.util.List;

import com.ymhw.website.model.base.BaseWelfare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Welfare extends BaseWelfare<Welfare> {
	public static final Welfare dao = new Welfare();
	
	/**
	 * 查询对应id的公益项目
	 * @param id
	 * @return
	 */
	public Welfare queryById(int id)
	{
		return dao.findFirst("select * from welfare where isValid = 1 and id = ?", id);
	}
	public List<Welfare> queryList(int num)
	{
		return dao.find("select * from welfare where isValid = 1 order by publishTime desc limit ?", num);
	}
	
	public List<Welfare> queryByType(int type, int num) {
		return dao.find("select * from welfare where type = ? and isValid = 1 order by publishTime desc limit ?",type, num);
	}
	
	
	/**
	 * 查询最火的公益项目（转发量最多）
	 * @return
	 */
	public Welfare queryBestHot()
	{
		return dao.findFirst("select * from welfare where isValid = 1 and retransmissNum = (select max(retransmissNum) from welfare where isValid = 1)");
	}
	
	/**
	 * 查询即将结束的公益项目
	 * @return
	 */
	public Welfare queryIsStoping()
	{
		return dao.findFirst("select * from welfare where isValid = 1 order by deadline asc limit 1");
	}
	
	/**
	 * 查询最新的公益项目
	 * @return
	 */
	public Welfare queryBestNew()
	{
		List<Welfare> welfares = queryList(1);
		if (welfares.size() != 1)
		{
			return null;
		}
		else
		{
			return welfares.get(0);
		}
	}
	
	/**
	 * 查询用户最关注的公益项目
	 * @param authorId
	 * @return
	 */
	public Welfare queryBestMind(int authorId)
	{
		if (authorId == 0)
		{
			return dao.findFirst("select * from welfare where isValid = 1  order by publishTime asc limit 1");
		}
		return dao.findFirst("select * from welfare where isValid = 1 and author != ? order by publishTime desc limit 1", authorId);
	}
}
