package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setTypes(java.lang.String types) {
		set("types", types);
	}

	public java.lang.String getTypes() {
		return get("types");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setAuthor(java.lang.Integer author) {
		set("author", author);
	}

	public java.lang.Integer getAuthor() {
		return get("author");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public void setScanNum(java.lang.Integer scanNum) {
		set("scanNum", scanNum);
	}

	public java.lang.Integer getScanNum() {
		return get("scanNum");
	}

	public void setPraisedNum(java.lang.Integer praisedNum) {
		set("praisedNum", praisedNum);
	}

	public java.lang.Integer getPraisedNum() {
		return get("praisedNum");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
