package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarrentstatus<M extends BaseCarrentstatus<M>> extends Model<M> implements IBean {

	public void setCarId(java.lang.Integer carId) {
		set("carId", carId);
	}

	public java.lang.Integer getCarId() {
		return get("carId");
	}

	public void setDay(java.util.Date day) {
		set("day", day);
	}

	public java.util.Date getDay() {
		return get("day");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setRented(java.lang.Integer rented) {
		set("rented", rented);
	}

	public java.lang.Integer getRented() {
		return get("rented");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
