package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivityorderdetail<M extends BaseActivityorderdetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setActId(java.lang.Integer actId) {
		set("actId", actId);
	}

	public java.lang.Integer getActId() {
		return get("actId");
	}

	public void setProName(java.lang.String proName) {
		set("proName", proName);
	}

	public java.lang.String getProName() {
		return get("proName");
	}

	public void setProDesc(java.lang.String proDesc) {
		set("proDesc", proDesc);
	}

	public java.lang.String getProDesc() {
		return get("proDesc");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}

	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setAdultNum(java.lang.Integer adultNum) {
		set("adultNum", adultNum);
	}

	public java.lang.Integer getAdultNum() {
		return get("adultNum");
	}

	public void setChildNum(java.lang.Integer childNum) {
		set("childNum", childNum);
	}

	public java.lang.Integer getChildNum() {
		return get("childNum");
	}

	public void setLmName(java.lang.String lmName) {
		set("lmName", lmName);
	}

	public java.lang.String getLmName() {
		return get("lmName");
	}

	public void setLmNumber(java.lang.String lmNumber) {
		set("lmNumber", lmNumber);
	}

	public java.lang.String getLmNumber() {
		return get("lmNumber");
	}

	public void setLmCertType(java.lang.Integer lmCertType) {
		set("lmCertType", lmCertType);
	}

	public java.lang.Integer getLmCertType() {
		return get("lmCertType");
	}

	public void setLmCertNumber(java.lang.String lmCertNumber) {
		set("lmCertNumber", lmCertNumber);
	}

	public java.lang.String getLmCertNumber() {
		return get("lmCertNumber");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
