package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSignup<M extends BaseSignup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setActId(java.lang.Integer actId) {
		set("actId", actId);
	}

	public java.lang.Integer getActId() {
		return get("actId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setAdultNum(java.lang.Integer adultNum) {
		set("adultNum", adultNum);
	}

	public java.lang.Integer getAdultNum() {
		return get("adultNum");
	}

	public void setChildNum(java.lang.Integer childNum) {
		set("childNum", childNum);
	}

	public java.lang.Integer getChildNum() {
		return get("childNum");
	}

	public void setLmName(java.lang.String lmName) {
		set("lmName", lmName);
	}

	public java.lang.String getLmName() {
		return get("lmName");
	}

	public void setLmNumber(java.lang.String lmNumber) {
		set("lmNumber", lmNumber);
	}

	public java.lang.String getLmNumber() {
		return get("lmNumber");
	}

	public void setLmEmail(java.lang.String lmEmail) {
		set("lmEmail", lmEmail);
	}

	public java.lang.String getLmEmail() {
		return get("lmEmail");
	}

	public void setLmQq(java.lang.String lmQq) {
		set("lmQq", lmQq);
	}

	public java.lang.String getLmQq() {
		return get("lmQq");
	}

	public void setTotalCost(java.lang.Float totalCost) {
		set("totalCost", totalCost);
	}

	public java.lang.Float getTotalCost() {
		return get("totalCost");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
