package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFarmstay<M extends BaseFarmstay<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDestinationId(java.lang.Integer destinationId) {
		set("destinationId", destinationId);
	}

	public java.lang.Integer getDestinationId() {
		return get("destinationId");
	}

	public void setShopName(java.lang.String shopName) {
		set("shopName", shopName);
	}

	public java.lang.String getShopName() {
		return get("shopName");
	}

	public void setServiceStartTime(java.lang.String serviceStartTime) {
		set("serviceStartTime", serviceStartTime);
	}

	public java.lang.String getServiceStartTime() {
		return get("serviceStartTime");
	}

	public void setServiceEndTime(java.lang.String serviceEndTime) {
		set("serviceEndTime", serviceEndTime);
	}

	public java.lang.String getServiceEndTime() {
		return get("serviceEndTime");
	}

	public void setParkInfo(java.lang.String parkInfo) {
		set("parkInfo", parkInfo);
	}

	public java.lang.String getParkInfo() {
		return get("parkInfo");
	}

	public void setSpecialAct(java.lang.String specialAct) {
		set("specialAct", specialAct);
	}

	public java.lang.String getSpecialAct() {
		return get("specialAct");
	}

	public void setOtherEquip(java.lang.String otherEquip) {
		set("otherEquip", otherEquip);
	}

	public java.lang.String getOtherEquip() {
		return get("otherEquip");
	}

	public void setAddedService(java.lang.String addedService) {
		set("addedService", addedService);
	}

	public java.lang.String getAddedService() {
		return get("addedService");
	}

	public void setAttention(java.lang.String attention) {
		set("attention", attention);
	}

	public java.lang.String getAttention() {
		return get("attention");
	}

	public void setCost(java.lang.Float cost) {
		set("cost", cost);
	}

	public java.lang.Float getCost() {
		return get("cost");
	}

	public void setFeePart(java.lang.String feePart) {
		set("feePart", feePart);
	}

	public java.lang.String getFeePart() {
		return get("feePart");
	}

	public void setProductDesc(java.lang.String productDesc) {
		set("productDesc", productDesc);
	}

	public java.lang.String getProductDesc() {
		return get("productDesc");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setCommentScore(java.lang.Integer commentScore) {
		set("commentScore", commentScore);
	}

	public java.lang.Integer getCommentScore() {
		return get("commentScore");
	}

	public void setCommentNum(java.lang.Integer commentNum) {
		set("commentNum", commentNum);
	}

	public java.lang.Integer getCommentNum() {
		return get("commentNum");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
