package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInfoTag<M extends BaseInfoTag<M>> extends Model<M> implements IBean {

	public void setTagId(java.lang.Integer tagId) {
		set("tag_id", tagId);
	}

	public java.lang.Integer getTagId() {
		return get("tag_id");
	}

	public void setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
	}

	public java.lang.String getTagName() {
		return get("tag_name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
