package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarorderdetail<M extends BaseCarorderdetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setCarId(java.lang.Integer carId) {
		set("carId", carId);
	}

	public java.lang.Integer getCarId() {
		return get("carId");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setLmname(java.lang.String lmname) {
		set("lmname", lmname);
	}

	public java.lang.String getLmname() {
		return get("lmname");
	}

	public void setLmnameIdcard(java.lang.String lmnameIdcard) {
		set("lmnameIdcard", lmnameIdcard);
	}

	public java.lang.String getLmnameIdcard() {
		return get("lmnameIdcard");
	}

	public void setLmnameTel(java.lang.String lmnameTel) {
		set("lmnameTel", lmnameTel);
	}

	public java.lang.String getLmnameTel() {
		return get("lmnameTel");
	}

	public void setRentStartTime(java.util.Date rentStartTime) {
		set("rentStartTime", rentStartTime);
	}

	public java.util.Date getRentStartTime() {
		return get("rentStartTime");
	}

	public void setRentEndTime(java.util.Date rentEndTime) {
		set("rentEndTime", rentEndTime);
	}

	public java.util.Date getRentEndTime() {
		return get("rentEndTime");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
