package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}

	public java.lang.String getTelphone() {
		return get("telphone");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setHeadshot(java.lang.String headshot) {
		set("headshot", headshot);
	}

	public java.lang.String getHeadshot() {
		return get("headshot");
	}

	public void setFixedNumber(java.lang.String fixedNumber) {
		set("fixedNumber", fixedNumber);
	}

	public java.lang.String getFixedNumber() {
		return get("fixedNumber");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setCertificateType(java.lang.Integer certificateType) {
		set("certificateType", certificateType);
	}

	public java.lang.Integer getCertificateType() {
		return get("certificateType");
	}

	public void setCertificateNum(java.lang.String certificateNum) {
		set("certificateNum", certificateNum);
	}

	public java.lang.String getCertificateNum() {
		return get("certificateNum");
	}

	public void setCountry(java.lang.Integer country) {
		set("country", country);
	}

	public java.lang.Integer getCountry() {
		return get("country");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setEmergencyPerson(java.lang.String emergencyPerson) {
		set("emergencyPerson", emergencyPerson);
	}

	public java.lang.String getEmergencyPerson() {
		return get("emergencyPerson");
	}

	public void setEmergencyPhone(java.lang.String emergencyPhone) {
		set("emergencyPhone", emergencyPhone);
	}

	public java.lang.String getEmergencyPhone() {
		return get("emergencyPhone");
	}

	public void setEmergencyRelation(java.lang.Integer emergencyRelation) {
		set("emergencyRelation", emergencyRelation);
	}

	public java.lang.Integer getEmergencyRelation() {
		return get("emergencyRelation");
	}

	public void setCertificateFront(java.lang.String certificateFront) {
		set("certificateFront", certificateFront);
	}

	public java.lang.String getCertificateFront() {
		return get("certificateFront");
	}

	public void setCertificateBack(java.lang.String certificateBack) {
		set("certificateBack", certificateBack);
	}

	public java.lang.String getCertificateBack() {
		return get("certificateBack");
	}

	public void setCertificateHander(java.lang.String certificateHander) {
		set("certificateHander", certificateHander);
	}

	public java.lang.String getCertificateHander() {
		return get("certificateHander");
	}

	public void setOtherCertificate(java.lang.String otherCertificate) {
		set("otherCertificate", otherCertificate);
	}

	public java.lang.String getOtherCertificate() {
		return get("otherCertificate");
	}

	public void setMotto(java.lang.String motto) {
		set("motto", motto);
	}

	public java.lang.String getMotto() {
		return get("motto");
	}

	public void setOutdoorExperience(java.lang.String outdoorExperience) {
		set("outdoorExperience", outdoorExperience);
	}

	public java.lang.String getOutdoorExperience() {
		return get("outdoorExperience");
	}

	public void setStudyExperience(java.lang.String studyExperience) {
		set("studyExperience", studyExperience);
	}

	public java.lang.String getStudyExperience() {
		return get("studyExperience");
	}

	public void setExperienceDoc(java.lang.String experienceDoc) {
		set("experienceDoc", experienceDoc);
	}

	public java.lang.String getExperienceDoc() {
		return get("experienceDoc");
	}

	public void setSellerName(java.lang.String sellerName) {
		set("sellerName", sellerName);
	}

	public java.lang.String getSellerName() {
		return get("sellerName");
	}

	public void setLegalmanName(java.lang.String legalmanName) {
		set("legalmanName", legalmanName);
	}

	public java.lang.String getLegalmanName() {
		return get("legalmanName");
	}

	public void setLmPID(java.lang.String lmPID) {
		set("lmPID", lmPID);
	}

	public java.lang.String getLmPID() {
		return get("lmPID");
	}

	public void setLmPhone(java.lang.String lmPhone) {
		set("lmPhone", lmPhone);
	}

	public java.lang.String getLmPhone() {
		return get("lmPhone");
	}

	public void setParterName(java.lang.String parterName) {
		set("parterName", parterName);
	}

	public java.lang.String getParterName() {
		return get("parterName");
	}

	public void setParterPIN(java.lang.String parterPIN) {
		set("parterPIN", parterPIN);
	}

	public java.lang.String getParterPIN() {
		return get("parterPIN");
	}

	public void setParterPhone(java.lang.String parterPhone) {
		set("parterPhone", parterPhone);
	}

	public java.lang.String getParterPhone() {
		return get("parterPhone");
	}

	public void setOrganCode(java.lang.String organCode) {
		set("organCode", organCode);
	}

	public java.lang.String getOrganCode() {
		return get("organCode");
	}

	public void setBankNo(java.lang.String bankNo) {
		set("bankNo", bankNo);
	}

	public java.lang.String getBankNo() {
		return get("bankNo");
	}

	public void setAlipayNo(java.lang.String alipayNo) {
		set("alipayNo", alipayNo);
	}

	public java.lang.String getAlipayNo() {
		return get("alipayNo");
	}

	public void setIdcardPic(java.lang.String idcardPic) {
		set("idcardPic", idcardPic);
	}

	public java.lang.String getIdcardPic() {
		return get("idcardPic");
	}

	public void setPraisedNum(java.lang.Integer praisedNum) {
		set("praisedNum", praisedNum);
	}

	public java.lang.Integer getPraisedNum() {
		return get("praisedNum");
	}

	public void setCheckStatus(java.lang.Integer checkStatus) {
		set("checkStatus", checkStatus);
	}

	public java.lang.Integer getCheckStatus() {
		return get("checkStatus");
	}

	public void setCheckMsg(java.lang.String checkMsg) {
		set("checkMsg", checkMsg);
	}

	public java.lang.String getCheckMsg() {
		return get("checkMsg");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
