package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarfactory<M extends BaseCarfactory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setLmname(java.lang.String lmname) {
		set("lmname", lmname);
	}

	public java.lang.String getLmname() {
		return get("lmname");
	}

	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setProvice(java.lang.String provice) {
		set("provice", provice);
	}

	public java.lang.String getProvice() {
		return get("provice");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public void setStreetAddress(java.lang.String streetAddress) {
		set("streetAddress", streetAddress);
	}

	public java.lang.String getStreetAddress() {
		return get("streetAddress");
	}

	public void setCheckStatus(java.lang.Integer checkStatus) {
		set("checkStatus", checkStatus);
	}

	public java.lang.Integer getCheckStatus() {
		return get("checkStatus");
	}

	public void setCheckMsg(java.lang.String checkMsg) {
		set("checkMsg", checkMsg);
	}

	public java.lang.String getCheckMsg() {
		return get("checkMsg");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

}
