package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInfoModule<M extends BaseInfoModule<M>> extends Model<M> implements IBean {

	public void setInfoModuleId(java.lang.Integer infoModuleId) {
		set("info_module_id", infoModuleId);
	}

	public java.lang.Integer getInfoModuleId() {
		return get("info_module_id");
	}

	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}

	public java.lang.String getModuleName() {
		return get("module_name");
	}

	public void setModuleType(java.lang.Integer moduleType) {
		set("module_type", moduleType);
	}

	public java.lang.Integer getModuleType() {
		return get("module_type");
	}

	public void setModuleContent(java.lang.String moduleContent) {
		set("module_content", moduleContent);
	}

	public java.lang.String getModuleContent() {
		return get("module_content");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

}
