package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setProposeTime(java.util.Date proposeTime) {
		set("proposeTime", proposeTime);
	}

	public java.util.Date getProposeTime() {
		return get("proposeTime");
	}

	public void setFeedbackContent(java.lang.String feedbackContent) {
		set("feedbackContent", feedbackContent);
	}

	public java.lang.String getFeedbackContent() {
		return get("feedbackContent");
	}

	public void setFeedbackTime(java.util.Date feedbackTime) {
		set("feedbackTime", feedbackTime);
	}

	public java.util.Date getFeedbackTime() {
		return get("feedbackTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
