package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInfo<M extends BaseInfo<M>> extends Model<M> implements IBean {

	public void setInfoId(java.lang.Integer infoId) {
		set("info_id", infoId);
	}

	public java.lang.Integer getInfoId() {
		return get("info_id");
	}

	public void setSubject(java.lang.String subject) {
		set("subject", subject);
	}

	public java.lang.String getSubject() {
		return get("subject");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setStar(java.lang.Integer star) {
		set("star", star);
	}

	public java.lang.Integer getStar() {
		return get("star");
	}

	public void setSubjectImg(java.lang.String subjectImg) {
		set("subjectImg", subjectImg);
	}

	public java.lang.String getSubjectImg() {
		return get("subjectImg");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setOpenStartTime(java.lang.String openStartTime) {
		set("openStartTime", openStartTime);
	}

	public java.lang.String getOpenStartTime() {
		return get("openStartTime");
	}

	public void setOpenEndTime(java.lang.String openEndTime) {
		set("openEndTime", openEndTime);
	}

	public java.lang.String getOpenEndTime() {
		return get("openEndTime");
	}

	public void setTravelSeason(java.lang.String travelSeason) {
		set("travelSeason", travelSeason);
	}

	public java.lang.String getTravelSeason() {
		return get("travelSeason");
	}

	public void setDuration(java.lang.String duration) {
		set("duration", duration);
	}

	public java.lang.String getDuration() {
		return get("duration");
	}

	public void setContactNumber(java.lang.String contactNumber) {
		set("contactNumber", contactNumber);
	}

	public java.lang.String getContactNumber() {
		return get("contactNumber");
	}

	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}

	public java.lang.Integer getGrade() {
		return get("grade");
	}

	public void setTotalPrice(java.lang.Float totalPrice) {
		set("totalPrice", totalPrice);
	}

	public java.lang.Float getTotalPrice() {
		return get("totalPrice");
	}

	public void setProvice(java.lang.String provice) {
		set("provice", provice);
	}

	public java.lang.String getProvice() {
		return get("provice");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public void setStreetAddress(java.lang.String streetAddress) {
		set("streetAddress", streetAddress);
	}

	public java.lang.String getStreetAddress() {
		return get("streetAddress");
	}

	public void setTransportInfo(java.lang.String transportInfo) {
		set("transportInfo", transportInfo);
	}

	public java.lang.String getTransportInfo() {
		return get("transportInfo");
	}

	public void setCommentScore(java.lang.Integer commentScore) {
		set("commentScore", commentScore);
	}

	public java.lang.Integer getCommentScore() {
		return get("commentScore");
	}

	public void setCommentNum(java.lang.Integer commentNum) {
		set("commentNum", commentNum);
	}

	public java.lang.Integer getCommentNum() {
		return get("commentNum");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
