package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEquip<M extends BaseEquip<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTypes(java.lang.String types) {
		set("types", types);
	}

	public java.lang.String getTypes() {
		return get("types");
	}

	public void setEquipPic(java.lang.String equipPic) {
		set("equipPic", equipPic);
	}

	public java.lang.String getEquipPic() {
		return get("equipPic");
	}

	public void setDeposit(java.lang.Float deposit) {
		set("deposit", deposit);
	}

	public java.lang.Float getDeposit() {
		return get("deposit");
	}

	public void setRent(java.lang.Float rent) {
		set("rent", rent);
	}

	public java.lang.Float getRent() {
		return get("rent");
	}

	public void setDirections(java.lang.String directions) {
		set("directions", directions);
	}

	public java.lang.String getDirections() {
		return get("directions");
	}

	public void setAttention(java.lang.String attention) {
		set("attention", attention);
	}

	public java.lang.String getAttention() {
		return get("attention");
	}

	public void setShowPrice(java.lang.String showPrice) {
		set("showPrice", showPrice);
	}

	public java.lang.String getShowPrice() {
		return get("showPrice");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setFixnumber(java.lang.String fixnumber) {
		set("fixnumber", fixnumber);
	}

	public java.lang.String getFixnumber() {
		return get("fixnumber");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setProvice(java.lang.String provice) {
		set("provice", provice);
	}

	public java.lang.String getProvice() {
		return get("provice");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public void setStreet(java.lang.String street) {
		set("street", street);
	}

	public java.lang.String getStreet() {
		return get("street");
	}

	public void setSendWay(java.lang.Integer sendWay) {
		set("sendWay", sendWay);
	}

	public java.lang.Integer getSendWay() {
		return get("sendWay");
	}

	public void setRentWay(java.lang.Integer rentWay) {
		set("rentWay", rentWay);
	}

	public java.lang.Integer getRentWay() {
		return get("rentWay");
	}

	public void setProvider(java.lang.Integer provider) {
		set("provider", provider);
	}

	public java.lang.Integer getProvider() {
		return get("provider");
	}

	public void setSupplyTension(java.lang.Integer supplyTension) {
		set("supplyTension", supplyTension);
	}

	public java.lang.Integer getSupplyTension() {
		return get("supplyTension");
	}

	public void setDamage(java.lang.String damage) {
		set("damage", damage);
	}

	public java.lang.String getDamage() {
		return get("damage");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setRentedNum(java.lang.Integer rentedNum) {
		set("rentedNum", rentedNum);
	}

	public java.lang.Integer getRentedNum() {
		return get("rentedNum");
	}

	public void setUploader(java.lang.Integer uploader) {
		set("uploader", uploader);
	}

	public java.lang.Integer getUploader() {
		return get("uploader");
	}

	public void setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
	}

	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public void setCheckStatus(java.lang.Integer checkStatus) {
		set("checkStatus", checkStatus);
	}

	public java.lang.Integer getCheckStatus() {
		return get("checkStatus");
	}

	public void setCheckMsg(java.lang.String checkMsg) {
		set("checkMsg", checkMsg);
	}

	public java.lang.String getCheckMsg() {
		return get("checkMsg");
	}

	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("isRecommend", isRecommend);
	}

	public java.lang.Integer getIsRecommend() {
		return get("isRecommend");
	}

	public void setTop(java.lang.Integer top) {
		set("top", top);
	}

	public java.lang.Integer getTop() {
		return get("top");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
