package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHotel<M extends BaseHotel<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDestinationId(java.lang.Integer destinationId) {
		set("destinationId", destinationId);
	}

	public java.lang.Integer getDestinationId() {
		return get("destinationId");
	}

	public void setHouseType(java.lang.String houseType) {
		set("houseType", houseType);
	}

	public java.lang.String getHouseType() {
		return get("houseType");
	}

	public void setBedType(java.lang.String bedType) {
		set("bedType", bedType);
	}

	public java.lang.String getBedType() {
		return get("bedType");
	}

	public void setAboutEquip(java.lang.String aboutEquip) {
		set("aboutEquip", aboutEquip);
	}

	public java.lang.String getAboutEquip() {
		return get("aboutEquip");
	}

	public void setParkInfo(java.lang.String parkInfo) {
		set("parkInfo", parkInfo);
	}

	public java.lang.String getParkInfo() {
		return get("parkInfo");
	}

	public void setProvice(java.lang.String provice) {
		set("provice", provice);
	}

	public java.lang.String getProvice() {
		return get("provice");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setRegion(java.lang.String region) {
		set("region", region);
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public void setStreetAddress(java.lang.String streetAddress) {
		set("streetAddress", streetAddress);
	}

	public java.lang.String getStreetAddress() {
		return get("streetAddress");
	}

	public void setFeePart(java.lang.String feePart) {
		set("feePart", feePart);
	}

	public java.lang.String getFeePart() {
		return get("feePart");
	}

	public void setCheckinType(java.lang.String checkinType) {
		set("checkinType", checkinType);
	}

	public java.lang.String getCheckinType() {
		return get("checkinType");
	}

	public void setIsCheckout(java.lang.Integer isCheckout) {
		set("isCheckout", isCheckout);
	}

	public java.lang.Integer getIsCheckout() {
		return get("isCheckout");
	}

	public void setTransportTip(java.lang.String transportTip) {
		set("transportTip", transportTip);
	}

	public java.lang.String getTransportTip() {
		return get("transportTip");
	}

	public void setAboutService(java.lang.String aboutService) {
		set("aboutService", aboutService);
	}

	public java.lang.String getAboutService() {
		return get("aboutService");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
