package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCar<M extends BaseCar<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setFactoryId(java.lang.Integer factoryId) {
		set("factoryId", factoryId);
	}

	public java.lang.Integer getFactoryId() {
		return get("factoryId");
	}

	public void setGearType(java.lang.Integer gearType) {
		set("gearType", gearType);
	}

	public java.lang.Integer getGearType() {
		return get("gearType");
	}

	public void setCntLimit(java.lang.Integer cntLimit) {
		set("cntLimit", cntLimit);
	}

	public java.lang.Integer getCntLimit() {
		return get("cntLimit");
	}

	public void setSweptVolume(java.lang.String sweptVolume) {
		set("sweptVolume", sweptVolume);
	}

	public java.lang.String getSweptVolume() {
		return get("sweptVolume");
	}

	public void setPrice(java.lang.Float price) {
		set("price", price);
	}

	public java.lang.Float getPrice() {
		return get("price");
	}

	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	public java.lang.Integer getTotal() {
		return get("total");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setShowpic(java.lang.String showpic) {
		set("showpic", showpic);
	}

	public java.lang.String getShowpic() {
		return get("showpic");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
