package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductorderdetail<M extends BaseProductorderdetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setProId(java.lang.Integer proId) {
		set("proId", proId);
	}

	public java.lang.Integer getProId() {
		return get("proId");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setLmname(java.lang.String lmname) {
		set("lmname", lmname);
	}

	public java.lang.String getLmname() {
		return get("lmname");
	}

	public void setLmnameTel(java.lang.String lmnameTel) {
		set("lmnameTel", lmnameTel);
	}

	public java.lang.String getLmnameTel() {
		return get("lmnameTel");
	}

	public void setLastUpdateTime(java.util.Date lastUpdateTime) {
		set("lastUpdateTime", lastUpdateTime);
	}

	public java.util.Date getLastUpdateTime() {
		return get("lastUpdateTime");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
