package com.ymhw.website.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setProperty(java.lang.Integer property) {
		set("property", property);
	}

	public java.lang.Integer getProperty() {
		return get("property");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setGatherPlace(java.lang.String gatherPlace) {
		set("gatherPlace", gatherPlace);
	}

	public java.lang.String getGatherPlace() {
		return get("gatherPlace");
	}

	public void setDeparturePlace(java.lang.String departurePlace) {
		set("departurePlace", departurePlace);
	}

	public java.lang.String getDeparturePlace() {
		return get("departurePlace");
	}

	public void setDestination(java.lang.String destination) {
		set("destination", destination);
	}

	public java.lang.String getDestination() {
		return get("destination");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
	}

	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setDeadline(java.util.Date deadline) {
		set("deadline", deadline);
	}

	public java.util.Date getDeadline() {
		return get("deadline");
	}

	public void setGatherTime(java.util.Date gatherTime) {
		set("gatherTime", gatherTime);
	}

	public java.util.Date getGatherTime() {
		return get("gatherTime");
	}

	public void setIntensityLevel(java.lang.Integer intensityLevel) {
		set("intensityLevel", intensityLevel);
	}

	public java.lang.Integer getIntensityLevel() {
		return get("intensityLevel");
	}

	public void setScenicSpot(java.lang.String scenicSpot) {
		set("scenicSpot", scenicSpot);
	}

	public java.lang.String getScenicSpot() {
		return get("scenicSpot");
	}

	public void setTotalNum(java.lang.Integer totalNum) {
		set("totalNum", totalNum);
	}

	public java.lang.Integer getTotalNum() {
		return get("totalNum");
	}

	public void setEnteredNum(java.lang.Integer enteredNum) {
		set("enteredNum", enteredNum);
	}

	public java.lang.Integer getEnteredNum() {
		return get("enteredNum");
	}

	public void setConfirmedNum(java.lang.Integer confirmedNum) {
		set("confirmedNum", confirmedNum);
	}

	public java.lang.Integer getConfirmedNum() {
		return get("confirmedNum");
	}

	public void setContactnumber(java.lang.String contactnumber) {
		set("contactnumber", contactnumber);
	}

	public java.lang.String getContactnumber() {
		return get("contactnumber");
	}

	public void setVehicle(java.lang.Integer vehicle) {
		set("vehicle", vehicle);
	}

	public java.lang.Integer getVehicle() {
		return get("vehicle");
	}

	public void setQqGroup(java.lang.String qqGroup) {
		set("qqGroup", qqGroup);
	}

	public java.lang.String getQqGroup() {
		return get("qqGroup");
	}

	public void setCost(java.lang.Float cost) {
		set("cost", cost);
	}

	public java.lang.Float getCost() {
		return get("cost");
	}

	public void setChildCost(java.lang.Float childCost) {
		set("childCost", childCost);
	}

	public java.lang.Float getChildCost() {
		return get("childCost");
	}

	public void setDisount(java.lang.Float disount) {
		set("disount", disount);
	}

	public java.lang.Float getDisount() {
		return get("disount");
	}

	public void setDiscountPrice(java.lang.Float discountPrice) {
		set("discountPrice", discountPrice);
	}

	public java.lang.Float getDiscountPrice() {
		return get("discountPrice");
	}

	public void setRouteDesc(java.lang.String routeDesc) {
		set("routeDesc", routeDesc);
	}

	public java.lang.String getRouteDesc() {
		return get("routeDesc");
	}

	public void setTravelPlan(java.lang.String travelPlan) {
		set("travelPlan", travelPlan);
	}

	public java.lang.String getTravelPlan() {
		return get("travelPlan");
	}

	public void setRequiredEquip(java.lang.String requiredEquip) {
		set("requiredEquip", requiredEquip);
	}

	public java.lang.String getRequiredEquip() {
		return get("requiredEquip");
	}

	public void setNotice(java.lang.String notice) {
		set("notice", notice);
	}

	public java.lang.String getNotice() {
		return get("notice");
	}

	public void setFeeDesc(java.lang.String feeDesc) {
		set("feeDesc", feeDesc);
	}

	public java.lang.String getFeeDesc() {
		return get("feeDesc");
	}

	public void setEnroll(java.lang.String enroll) {
		set("enroll", enroll);
	}

	public java.lang.String getEnroll() {
		return get("enroll");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setTakers(java.lang.String takers) {
		set("takers", takers);
	}

	public java.lang.String getTakers() {
		return get("takers");
	}

	public void setLeaders(java.lang.String leaders) {
		set("leaders", leaders);
	}

	public java.lang.String getLeaders() {
		return get("leaders");
	}

	public void setTop(java.lang.Integer top) {
		set("top", top);
	}

	public java.lang.Integer getTop() {
		return get("top");
	}

	public void setIsRecommend(java.lang.Integer isRecommend) {
		set("isRecommend", isRecommend);
	}

	public java.lang.Integer getIsRecommend() {
		return get("isRecommend");
	}

	public void setCheckStatus(java.lang.Integer checkStatus) {
		set("checkStatus", checkStatus);
	}

	public java.lang.Integer getCheckStatus() {
		return get("checkStatus");
	}

	public void setCheckMsg(java.lang.String checkMsg) {
		set("checkMsg", checkMsg);
	}

	public java.lang.String getCheckMsg() {
		return get("checkMsg");
	}

	public void setIsValid(java.lang.Integer isValid) {
		set("isValid", isValid);
	}

	public java.lang.Integer getIsValid() {
		return get("isValid");
	}

}
